language: python
python:
  - "3.6"
  - "3.7-dev"  # 3.7 development branch
before_install:
  - sudo apt-get install -y libraw-dev libzbar-dev
install:
  - pip install -U -r tests/requirements.txt
script:
  - pytest --remote-data
