name: pyts2-dev
channels:
  - conda-forge
dependencies:
  - python=3.*
  - numpy
  - flask
  - imageio
  - msgpack-python
  - iso8601
  - click
  - zbarlight
  - pytest
  - pytest-remotedata
  - requests
  - pip:
    - rawpy
    - tqdm
    - datetime_truncate
