name: pyts2-dev
channels:
  - conda-forge
dependencies:
  - python=3.*
  - click
  - dulwich
  - fasteners
  - flask
  - imageio
  - iso8601
  - msgpack-python
  - numpy
  - opencv
  - pytest
  - pytest-cov
  - pytest-remotedata
  - requests
  - scikit-image
  - zbarlight
  - pip
  - pip:
    - rawpy
    - tqdm
    - datetime_truncate
